# Generated by Django 4.2 on 2024-04-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', '여성'), ('M', '남성'), ('O', '기타')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
